<?php
namespace Noodlehaus\FileParser\Test;

use Noodlehaus\FileParser\Neon;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-04-21 at 22:37:22.
 */
class NeonTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var Neon
     */
    protected $neon;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->neon = new Neon();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Noodlehaus\FileParser\Neon::getSupportedExtensions()
     */
    public function testGetSupportedExtensions()
    {
        $expected = array('neon');
        $actual   = $this->neon->getSupportedExtensions();
        $this->assertEquals($expected, $actual);
    }

    /**
     * @covers                   Noodlehaus\FileParser\Neon::parse()
     * @expectedException        Noodlehaus\Exception\ParseException
     * @expectedExceptionMessage Error parsing NEON file
     */
    public function testLoadInvalidNeon()
    {
        $this->neon->parse(__DIR__ . '/../mocks/fail/error.neon');
    }

    /**
     * @covers Noodlehaus\FileParser\Neon::parse()
     */
    public function testLoadNeon()
    {
        $actual = $this->neon->parse(__DIR__ . '/../mocks/pass/config.neon');
        $this->assertEquals('localhost', $actual['host']);
        $this->assertEquals('80', $actual['port']);
    }
}
